# Replace with actual device IP and credentials
devices:
  - name: Palo1
    type: paloalto_panos
    ip: 192.168.1.1
    username: admin
    password: yourpass

  - name: ASA1
    type: cisco_asa
    ip: 192.168.1.2
    username: admin
    password: yourpass

  - name: Forti1
    type: fortinet
    ip: 192.168.1.3
    username: admin
    password: yourpass

  - name: Juniper1
    type: juniper
    ip: 192.168.1.4
    username: admin
    password: yourpass

  - name: pfSense1
    type: linux     # or generic_termserver
    ip: 192.168.1.6
    username: admin
    password: yourpass

  - name: F5_1
    type: f5_tmsh   # or f5_linux
    ip: 192.168.1.7
    username: admin
    password: yourpass

  - name: Infoblox1
    type: infoblox
    ip: 192.168.1.8
    username: admin
    password: yourpass

  - name: Zscaler1
    type: zscaler
    ip: admin.zscalertwo.net
    username: apiuser
    password: apipassword

  - name: Checkpoint_CLI
    type: checkpoint_gaia
    ip: 192.168.100.10
    username: admin
    password: yourpass

  - name: Checkpoint_API
    type: checkpoint
    ip: 192.168.100.11
    username: apiadmin
    password: apipass


