configs:
  paloalto_panos:
    - set network interface ethernet1/1 layer3 ip 192.168.1.1/24
    - set network virtual-router default interface ethernet1/1
    - set network virtual-router default routing-table ip static-route myroute destination 10.10.10.0/24 nexthop ip-address 192.168.1.254
  fortinet:
    - config system interface
    - edit port1
    - set ip 192.168.1.1 255.255.255.0
    - next
    - end
    - config router static
    - edit 1
    - set dst 10.10.10.0 255.255.255.0
    - set gateway 192.168.1.254
    - next
    - end
  cisco_asa:
    - interface GigabitEthernet0/1
    - ip address 192.168.1.1 255.255.255.0
    - nameif inside
    - no shutdown
    - route inside 10.10.10.0 255.255.255.0 192.168.1.254
  juniper:
    - set interfaces ge-0/0/1 unit 0 family inet address 192.168.1.1/24
    - set routing-options static route 10.10.10.0/24 next-hop 192.168.1.254
  checkpoint_gaia:
    - set interface eth1 state on
    - set interface eth1 ipv4-address 192.168.1.1 subnet-mask 255.255.255.0
    - set static-route 10.10.10.0/24 nexthop gateway address 192.168.1.254 on
